language: cpp

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    exclude:
    -   os: osx
        compiler: gcc

addons:
    apt:
        packages:
            - libpng-dev

script: make libgambatte test && cd test && ./run_tests.sh
